// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Timestamps.DAL.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EditHourageModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditHourageModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201611290703320_EditHourageModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
